### PR TITLE
Add IF NOT EXISTS functionality to CreateTable & CreateSchema commands

### PR DESCRIPTION
**Pull request by robertengel**
/review @asherf @amathewhearsay @amathewhearsay

### CODE REVIEW

**Comment by asherf** [comment]
assuming we are going to have schemas per functionality (i.e. staging/reporting/data), do we need to be able to dynamically create them ? I think a migrations script to create schema(s) should do the job.

**Comment by robertengel** [comment]
I modified this primarily for having a CREATE TABLE IF NOT EXISTS construct. Why shouldn't I add this functionality for CREATE SCHEMA if I'm already at it?

**Comment by asherf** [comment]
I think SqlAlchemy can already do create if not exists on table. I think I used it.

**Comment by asherf** [comment]
lgtm

**Comment by robertengel** [comment]
The version we're using can't. It connects to and checks in the database whether the table exists before creation, which is inefficient.

**Comment by hearsaydev** [comment]
Attempting a merge on behalf of **rengel**. Stand clear!

**Pull request merged**
