### PR TITLE
Add capability for copying from DynamoDB to CopyCommand

### PR DESCRIPTION
**Pull request by robertengel**
/review @asherf @amathewhearsay @rogerhu

### CODE REVIEW

**Comment by asherf** [comment]
lgtm

**Comment by hearsaydev** [comment]
Attempting a merge on behalf of **rengel**. Stand clear!

**Comment by rogerhu** [comment]
We're PRing this stuff back to the main repo right?

**Comment by robertengel** [comment]
I was planning to check at some point how branches have diverged so far and decide upon this then.

**Pull request merged**
